globalmart:
  target: dev
  outputs:
    dev:
      dbt_version: 1.4.6
      type: snowflake
      account: qg35001.central-india.azure
      user: { { env_var('DBT_USER') } }
      password: { { env_var('DBT_ENV_SECRET_PWD') } }
      database: analytics
      warehouse: compute_wh
      schema: dbt_dev
      threads: 4
      client_session_keep_alive: false
    prod:
      dbt_version: 1.4.6
      type: snowflake
      account: qg35001.central-india.azure
      user: { { env_var('DBT_USER') } }
      password: { { env_var('DBT_ENV_SECRET_PWD') } }
      database: analytics
      warehouse: compute_wh
      schema: dbt_prod
      threads: 4
      client_session_keep_alive: false
