globalmart:

  target: dev
  outputs:
    dev:
      dbt_version: 1.4.6
      type: snowflake
      account: xd66785.central-india.azure
      user: themavathi
      password: Happy@001
      database: analytics
      warehouse: compute_wh
      schema: dbt_dev
      threads: 4
      client_session_keep_alive: false
    prod:
      dbt_version: 1.4.6
      type: snowflake
      account: xd66785.central-india.azure
      user: themavathi
      password: Happy@001
      database: analytics
      warehouse: compute_wh
      schema: dbt_prod
      threads: 4
      client_session_keep_alive: false
  

